/**
 * KronosDB event scheduler — server-side scheduled appends.
 *
 * Hands an event to the store now and has the store append it when due, with
 * no client left holding a timer. The schedule is durable the moment
 * `schedule()` resolves (quorum-acknowledged like any append), firing is
 * exactly-once across leader failover, and nothing polls: if the server is
 * up, due events land; if it is down, nothing else could append either, and
 * overdue schedules fire on recovery.
 *
 * The returned token is the handle for cancellation and the idempotency key:
 * supply your own via `options.token` to make a retried `schedule()` call
 * safe after a timeout.
 */
import {
  qualifiedNameToString,
  type Serializer,
} from "@kronos-ts/core"
import type { EventMessage } from "@kronos-ts/core"
import { Status } from "nice-grpc"
import type { KronosDbConnection } from "./connection.js"
import { kronosMetadata } from "./connection.js"
import { metadataToStringMap } from "./metadata-conversion.js"

const textEncoder = new TextEncoder()

/** A schedule that has neither fired nor been cancelled. */
export interface PendingSchedule {
  /** Token identifying the schedule for cancellation. */
  token: string
  /** When the event will be appended, in milliseconds since epoch. */
  dueAt: number
  /** Type name of the event that will be appended. */
  eventName: string
}

export interface ScheduleOptions {
  /**
   * Caller-supplied idempotency token. When set, retrying a timed-out
   * `schedule()` call cannot create a second schedule — the retry fails
   * with {@link ScheduleAlreadyExistsError}, which the caller can treat as
   * success. Generated by the server when omitted.
   */
  token?: string
}

/** The token is already in use — usually a retried `schedule()` call. */
export class ScheduleAlreadyExistsError extends Error {
  constructor(readonly token: string) {
    super(`A schedule with token '${token}' already exists`)
    this.name = "ScheduleAlreadyExistsError"
  }
}

/** The schedule has already resolved — fired or cancelled — so there was nothing to cancel. */
export class ScheduleAlreadyResolvedError extends Error {
  constructor(readonly token: string) {
    super(`Schedule '${token}' has already fired or been cancelled`)
    this.name = "ScheduleAlreadyResolvedError"
  }
}

/** No schedule with this token was ever created. */
export class ScheduleNotFoundError extends Error {
  constructor(readonly token: string) {
    super(`No schedule with token '${token}'`)
    this.name = "ScheduleNotFoundError"
  }
}

export interface KronosDbScheduler {
  /**
   * Schedules `event` to be appended when `dueAt` arrives. Returns the
   * schedule token. A due time in the past fires on the next scheduler tick.
   */
  schedule(event: EventMessage, dueAt: Date | number, options?: ScheduleOptions): Promise<string>

  /**
   * Cancels a schedule that has not yet fired.
   *
   * The race between a cancel and the event firing has exactly one winner:
   * if the event already landed, this throws
   * {@link ScheduleAlreadyResolvedError} rather than silently doing nothing,
   * so the caller knows the event is in the log and can compensate.
   */
  cancel(token: string): Promise<void>

  /** Lists schedules that have neither fired nor been cancelled, soonest first. */
  list(): Promise<PendingSchedule[]>
}

/**
 * Creates a scheduler backed by KronosDB's SchedulerService.
 *
 * Scheduling and cancelling must reach the leader node; in a cluster,
 * followers refuse with FAILED_PRECONDITION and the connection's failover
 * handles re-routing. Listing works on any node.
 */
export function createKronosDbScheduler(
  connection: KronosDbConnection,
  serializer: Serializer,
): KronosDbScheduler {
  function getMetadata() {
    return kronosMetadata(connection.config)
  }

  return {
    async schedule(event, dueAt, options) {
      const name = qualifiedNameToString(event.name)
      const serialized = serializer.serialize(event.payload, name, event.version)
      const dueMs = typeof dueAt === "number" ? dueAt : dueAt.getTime()

      try {
        const response = await connection.scheduler.scheduleAppend(
          {
            dueMs: BigInt(dueMs),
            token: options?.token ?? "",
            event: {
              event: {
                identifier: event.identifier,
                // Advisory: the server stamps the actual append time when
                // the schedule fires.
                timestamp: BigInt(event.timestamp),
                name,
                version: event.version,
                payload: serialized.data,
                metadata: metadataToStringMap(event.metadata),
              },
              tags: event.tags.map((tag) => ({
                key: textEncoder.encode(tag.key),
                value: textEncoder.encode(tag.value),
              })),
            },
          },
          { metadata: getMetadata() },
        )
        return response.token
      } catch (error) {
        if (isGrpcStatus(error, Status.ALREADY_EXISTS)) {
          throw new ScheduleAlreadyExistsError(options?.token ?? "")
        }
        throw error
      }
    },

    async cancel(token) {
      try {
        await connection.scheduler.cancelSchedule({ token }, { metadata: getMetadata() })
      } catch (error) {
        if (isGrpcStatus(error, Status.FAILED_PRECONDITION)) {
          throw new ScheduleAlreadyResolvedError(token)
        }
        if (isGrpcStatus(error, Status.NOT_FOUND)) {
          throw new ScheduleNotFoundError(token)
        }
        throw error
      }
    },

    async list() {
      const response = await connection.scheduler.listSchedules({}, { metadata: getMetadata() })
      return response.schedules.map((schedule) => ({
        token: schedule.token,
        dueAt: Number(schedule.dueMs),
        eventName: schedule.eventName,
      }))
    },
  }
}

function isGrpcStatus(error: unknown, status: Status): boolean {
  return typeof error === "object" && error !== null && "code" in error && error.code === status
}
